apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aetherius

resources:
  - namespace.yaml
  - postgres/
  - redis/
  - rabbitmq/
  - minio/
  - services/
  - api-gateway/

commonLabels:
  app.kubernetes.io/part-of: aetherius
  app.kubernetes.io/managed-by: kustomize

configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml
